# Generated by Django 4.1.7 on 2023-05-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CopperProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prd_name', models.CharField(max_length=25)),
                ('prd_qnty', models.IntegerField()),
                ('prd_validity', models.BooleanField(default=False)),
                ('prd_valid_upto', models.DateField()),
            ],
        ),
    ]
