# Generated by Django 4.1.7 on 2023-05-27 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='bouns',
            new_name='bonus',
        ),
    ]
